### ISSUE TITLE
Spice of life imcompatibility

### ISSUE THREAD

**Issue by Narwhal8** [defeatedcrow/HeatAndClimateLib#7]
Heatandclimatelib is not being affected by it and is not getting diminishing returns

**Comment by defeatedcrow** [comment]
They are not compatible. Moreover, there is no plan of correspondence.

Because it seems that Mod does not include API for compatibility. Probably, that Mod requires a configuration file created by the user. It seems I can not prepare.

**Comment by ghost** [comment]
Spice of life uses AppleCore. Integration steps are located at: https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore
I think to make compatible, DCFoodItem needs to use player.getFoodStats().addStats(this,stack); instead of player.getFoodStats().addStats(getFoodAmo(meta), getSaturation(meta));  as this passes the stack. Not sure how to add compatibility of food metadata

**Comment by defeatedcrow** [comment]
Thank you for the information! Next time I will try to refine DCFoodItem.class.

**Comment by defeatedcrow** [comment]
It fixed in d65f445.
